services:
  api:
    build:
      context: .
      target: builder
    container_name: tfjs-converter
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - type: bind
        source: ./
        target: /app
    restart: "no"
